name: chip_core
description: ChipFit Core - Core utilities (Cache, Delta Viewer, etc.)
publish_to: 'none'

environment:
  sdk: '^3.5.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  chip_dependencies:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_dependencies
  flutter_cache_manager:
  http:
  flutter_quill:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
