name: chip_foundation
description: ChipFit Foundation - Colors, TextStyles, Themes
publish_to: 'none'

environment:
  sdk: '^3.5.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  chip_assets:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_assets

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
