name: catalog
description: "ChipmunkStudio DesignSystem Catalog App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ChipFit 디자인 시스템
  chip_foundation:
    path: ../chip_foundation
  chip_component:
    path: ../chip_component
  chip_module:
    path: ../chip_module
  chip_assets:
    path: ../chip_assets
  chip_core:
    path: ../chip_core

  bloc_concurrency:
  flutter_bloc:
  side_effect_bloc:
  flutter_screenutil:
  bloc_event_transformers:
  bloc:
  go_router:
  toast:
  equatable:
  freezed:
  freezed_annotation:
  dartz:
  flutter_cache_manager:
  cached_network_image:
  flutter_animate:
  lottie:
  dotlottie_loader:
  flutter_svg:
  flutter_bounceable:
  flutter_quill:
  sprung:
  modal_bottom_sheet:
  animated_theme_switcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Pretendard-Light
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
    - family: Pretendard-Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
    - family: Pretendard-Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
    - family: Pretendard-SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
    - family: Pretendard-Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
    - family: Neodgm
      fonts:
        - asset: assets/fonts/neodgm.ttf
          weight: 400
