name: chip_component
description: ChipFit Component - UI Components
publish_to: 'none'

environment:
  sdk: '^3.5.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  chip_assets:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_assets
  chip_foundation:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_foundation
  chip_dependencies:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_dependencies
  cached_network_image:
  flutter_animate:
  lottie:
  dotlottie_loader:
  flutter_svg:
  flutter_bounceable:
  sprung:
  flutter_keyboard_visibility:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
