name: chip_module
description: ChipFit Module - Scaffold, Dialog, BottomSheet
publish_to: 'none'

environment:
  sdk: '^3.5.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  chip_assets:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_assets
  chip_foundation:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_foundation
  chip_component:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_component
  chip_dependencies:
    git:
      url: https://github.com/chipmunk-studio/chipmunk-fit.git
      ref: main
      path: chip_dependencies
  flutter_screenutil:
  flutter_bounceable:
  modal_bottom_sheet:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
